config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end
  
  def show
  end

  def create
    @article = Article.new(article_params)

    if 
      redrect_to @article, notice: "Article was successfull created"
    else
      render :new
    end

  end

  def edit
  end

  def destroy
    @article.destroy
    redirect_to @article, notice: "Article was successfully destroyed"
  end

  def update

    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated"
    else
      render
    end

  end

  private

  def set_article
    @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/application/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wikinimous", articles_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'New Article', new_article_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/articles/_form.html.erb
<%= bootstrap_form_for(@article, class: 'form') do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :content, data: { editor: 'markdown' }, rows: 10 %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <article>
    <h2><%= link_to article.title, article %></h2>
    <%= article.content[0..100] %>
  </article>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% content_for(:title) do %>
  Wikinimous - <%= @article.title %>
<% end %>

<article>
  <h1>
    <%= @article.title %>
    <small>
      <%= link_to edit_article_path(@article) do %><i class="fa fa-pencil"></i><% end %>

      <%= link_to article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </small>
  </h1>

  <hr>
  <%# <%= @article.markdown_content %> %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300|Roboto+Slab">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "navbar" %>

   <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <%= render "flash" %>

        <%= yield %>
      </div>
    </div>
  </div>

  </body>
</html>